# Generated by Django 3.2 on 2023-01-16 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='profile-images')),
                ('facebook_profile', models.CharField(max_length=80)),
                ('linkedin_profile', models.CharField(max_length=80)),
                ('website', models.CharField(max_length=80)),
            ],
        ),
    ]
