# Generated by Django 3.2 on 2023-02-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230209_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/media/profile-images/default_user_profile.png', null=True, upload_to='profile-images'),
        ),
    ]
