# Generated by Django 3.2 on 2023-02-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='https://gravatar.com/avatar/b58996c504c5638798eb6b511e6f49af?s=200&d=mp&r=x', null=True, upload_to=''),
        ),
    ]
