# Generated by Django 3.2 on 2023-03-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230301_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
