version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 443:8000
    volumes:
      - static-data:/vol/static
      - /certs:/vol/certs:ro # set the SELinux context of the volume
      - /etc/localtime:/etc/localtime:ro # sync timezones
      - /etc/timezone:/etc/timezone:ro
      - /home/ec2-user/certs/privkey.pem:/vol/certs/privkey.pem:ro,Z #  mount privkey.pem with read-only access
      - /home/ec2-user/certs/fullchain.pem:/vol/certs/fullchain.pem:ro,Z
    user: "nginx" # Add this line to set the user of the mounted volumes

volumes:
  postgres-data:
  static-data:


