version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=drutex
      - DB_USER=streleweb
      - DB_PASS=justforlocaldev
      - DEBUG=1
    depends_on:
      #waits for db service to start
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=drutex
      - POSTGRES_USER=streleweb
      - POSTGRES_PASSWORD=justforlocaldev
    ports:
      - '3306:3306'
    expose:
      - '3306'
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dev-db-data:
  .:


