# Generated by Django 3.2 on 2023-02-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, default='lightblue', max_length=9, null=True),
        ),
    ]
