---
name: Jobs

on: [push]

jobs:
  # test-lint:
  #   name: Test and lint
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USER }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Checkout
  #       uses: actions/checkout@v2 #checks code out inside (code made available)
  #     - name: Test
  #       run: docker-compose run --rm app sh -c "python manage.py test"
  #     - name: Linti
  #       run: docker-compose run --rm app sh -c "flake8"

  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2 #checks code out inside (code made available)
      - name: Set up Python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
      - name: activateVenv
        run: |
          pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
      - name: Test
        run: python manage.py test
      - name: Linti
        run: flake8
      - name: deactivateVenv
        run: deactivate